<a href="https://colab.research.google.com/github/20195114/Detectron/blob/main/2024_02_07_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# 배열 생성
ar = np.array([10, 2, 3, 4, np.nan, 32, 42])
# 배열에 None 데이터가 있는지 확인
print(np.isnan(ar)) #결측치 확인

# 결측치를 제외하고 가져오기
result = ar[np.logical_not(np.isnan(ar))]
print(result)

[False False False False  True False False]
[10.  2.  3.  4. 32. 42.]


In [ ]:
import numpy as np
ar = np.array([2, 5, 23, 34, 21, 42, np.nan, 25])
print(ar)

# 3의 배수이거나 4의 배수인 데이터만 추출 np.nan을 제거
temp = ar[np.logical_not(np.isnan(ar))]
result = temp[(temp % 3 == 0) | (temp % 4 == 0)]
print(result)


[ 2.  5. 23. 34. 21. 42. nan 25.]
[21. 42.]


In [ ]:
# 아래 데이터는 1, 2, 3, 4 중에 하나를 선택하는 범주형 데이터의 집합
# 이상함 값이 있는지 확인
ar = np.array([2, 1, 3, 4, 5, 1, 2, 3])
print(np.unique(ar))



[1 2 3 4 5]


In [ ]:
ar = np.array([2, 1, 3, 4, np.nan])
print(ar.sort())
print(ar)
# numpy 의 sort 는 리턴을 하고 ndarrat 의 sort 는 린턴하지 않습니다.
# 내림차순 정렬은 numpy의 sort를 이용하면 됩니다.
print(np.sort(ar)[::-1])
#2차원 배열은 numpy 에서는 sort를 잘 사용하지 않습니다.
# 데이터의 인덱스가 꺠져버립니다.
matrix = np.array([[1, 3, 2, 4] , [9, 4, 1, 8]])
matrix.sort(axis = 0)
print(matrix)

None
[ 1.  2.  3.  4. nan]
[nan  4.  3.  2.  1.]
[[1 3 1 4]
 [9 4 2 8]]


In [20]:
#hstack
ar = np.array([[1, 2, 3, ], [4, 5, 6]])
print(ar)
br = np.array([[11, 22, 33], [44, 55, 66]])
print(br)
print(np.hstack([ar, br]))
print(np.vstack([ar, br]))
print(np.dstack([ar, br]))


[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
[[[ 1 11]
  [ 2 22]
  [ 3 33]]

 [[ 4 44]
  [ 5 55]
  [ 6 66]]]


In [21]:
help(np.savez)

Help on function savez in module numpy:

savez(file, *args, **kwds)
    Save several arrays into a single file in uncompressed ``.npz`` format.
    
    Provide arrays as keyword arguments to store them under the
    corresponding name in the output file: ``savez(fn, x=x, y=y)``.
    
    If arrays are specified as positional arguments, i.e., ``savez(fn,
    x, y)``, their names will be `arr_0`, `arr_1`, etc.
    
    Parameters
    ----------
    file : str or file
        Either the filename (string) or an open file (file-like object)
        where the data will be saved. If file is a string or a Path, the
        ``.npz`` extension will be appended to the filename if it is not
        already there.
    args : Arguments, optional
        Arrays to save to the file. Please use keyword arguments (see
        `kwds` below) to assign names to arrays.  Arrays specified as
        args will be named "arr_0", "arr_1", and so on.
    kwds : Keyword arguments, optional
        Arrays to save

In [27]:
import pandas as pd
# 시리즈를 생성
price = pd.Series([1000, 3000, 2000, 4000])
# 시리즈를 출력 - 자동 생성된 인덱스 와 값이 출력
print(price)
# 0 이라는 인덱스를 가진 데이터를 조회
print(price[0])
# 인덱스를 직접 설정
price.index = ["사탕", "과자", "음료수", "과일"]
print(price)
# 인덱스가 사탕이라는 데이터를 조회 : 1000
print(price["사탕"])

0    1000
1    3000
2    2000
3    4000
dtype: int64
1000
사탕     1000
과자     3000
음료수    2000
과일     4000
dtype: int64
1000


In [38]:
x = (price["사탕":"음료수"]) # 사탕부터 음료수까지
# x의 데이터를 변경하면 원본인 price 의 데이터도 수정
x["사탕"] = 800
print(x)
print(price)
print("================================")
y = (price[["사탕","음료수"]]) #사탕과 음료수의 데이터를 복제해 온 것
# y 의 데이터를 변경해도 원본인 price의 데이터를 변경되지 않는 것
y["사탕"] = 2000
print(y)
print(price)
print(price[["사탕","음료수","과자"]])

사탕      800
과자     3000
음료수    2000
dtype: int64
사탕      800
과자     3000
음료수    2000
과일     4000
dtype: int64
사탕     2000
음료수    2000
dtype: int64
사탕      800
과자     3000
음료수    2000
과일     4000
dtype: int64
사탕      800
음료수    2000
과자     3000
dtype: int64


In [40]:
s1 = pd.Series([100, 200, 300, np.nan], index = ["사과", "배", "한라봉", "천혜향"])
print(s1)
s2 = pd.Series([100, 200, 300, 500], index = ["사과", "한라봉", "무화과", "천혜향"])
print(s2)

#시리즈는 인덱스가 일치하는 데이터끼리 연산을 수행합니다.
#한쪽에만 존재하거나 np.nan인 데이터가 있으면 결과가 np.nan이 됩니다.
print(s1 + s2)


사과     100.0
배      200.0
한라봉    300.0
천혜향      NaN
dtype: float64
사과     100
한라봉    200
무화과    300
천혜향    500
dtype: int64
무화과      NaN
배        NaN
사과     200.0
천혜향      NaN
한라봉    500.0
dtype: float64


In [45]:
import pandas as pd

source = {
    "code":[1, 2, 3, 4],
    "name":["카리나", "지젤", "닝닝", "윈터"],
    "age" : [23, 22, 34, 21]
}

df = pd.DataFrame(source)
print(df)

   code name  age
0     1  카리나   23
1     2   지젤   22
2     3   닝닝   34
3     4   윈터   21


In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   code    4 non-null      int64 
 1   name    4 non-null      object
 2   age     4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [49]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)


In [52]:
print(type(df.index))

<class 'pandas.core.indexes.range.RangeIndex'>
