<a href="https://colab.research.google.com/github/20195114/Detectron/blob/main/2024_02_16_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import files
myfile = files.upload()

Saving auto-mpg.csv to auto-mpg.csv


In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
!pip install pandas
import pandas as pd

df = pd.read_csv('/content/auto-mpg.csv')

In [38]:
mpg = pd.read_csv('/content/auto-mpg.csv', header=None)
mpg.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration','model year', 'origin', 'name']
print(mpg.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  


In [45]:
!pip install chardet

In [44]:
import chardet
import pandas as pd

In [46]:
with open('/content/student.csv', 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']

FileNotFoundError: [Errno 2] No such file or directory: '/content/student.csv'

In [41]:
students= pd.read_csv('/content/student.csv', encoding=encoding)
print(students)


NameError: name 'encoding' is not defined

In [42]:
# 막대 그래프 그리기
# 별다른 설정없이 그리면 한글이 출력되지 않음
students.plot(kind = 'bar')

NameError: name 'students' is not defined

In [99]:
# 이미지나 그래프에 한글 출력을 위한 설정
import matplotlib.pyplot as plt
import platform
import matplotlib as mpl
import matplotlib.font_manager as font_manager
from matplotlib import rc

if platform.system() == 'Darwin':
  rc('font', family = 'AppleGothic')


In [100]:
import pandas as pd
import numpy as np

In [40]:
students.plot(kind = 'bar')

NameError: name 'students' is not defined

In [112]:
!apt-cache search fonts-apple-gothic

In [118]:
import pandas as pd
import numpy as np

In [119]:
mpg = globals()['mpg']

In [139]:
from sklearn.preprocessing import Normalizer

feature = np.array([[1,2], [2,3], [4,3], [3,4]])

normalizer = Normalizer(norm='l2')

result = normalizer.transform(feature)
print(result)


[[0.4472136  0.89442719]
 [0.5547002  0.83205029]
 [0.8        0.6       ]
 [0.6        0.8       ]]


In [142]:
# 다항 및 교차항 특성 만들기
from sklearn.preprocessing import PolynomialFeatures

features = np.array([[2,3], [3,4], [1,5]])

polynomial_interaction = PolynomialFeatures(degree=2, include_bias= False)
result = polynomial_interaction.fit_transform(features)
print(result)

polynomial_interaction = PolynomialFeatures(degree=2, include_bias= True, interaction_only=True)
result = polynomial_interaction.fit_transform(features)
print(result)

[[ 2.  3.  4.  6.  9.]
 [ 3.  4.  9. 12. 16.]
 [ 1.  5.  1.  5. 25.]]
[[ 1.  2.  3.  6.]
 [ 1.  3.  4. 12.]
 [ 1.  1.  5.  5.]]


In [147]:
# 특성 변환
# 함수를 적용해서 데이터를 변경하는 것
from sklearn.preprocessing import FunctionTransformer

feature = np.array([[1,3], [3,6]])

#적용할 함수
def add_one(x:int) -> int:
  return x+1

#배열에 함수 적용
one_transformer = FunctionTransformer(add_one)
result = one_transformer.transform(feature)
print(result)

df = pd.DataFrame(feature, columns = ['f1', 'f2'])
print(df)
print(df.apply(add_one))

[[2 4]
 [4 7]]
   f1  f2
0   1   3
1   3   6
   f1  f2
0   2   4
1   4   7


In [37]:
# Import the numpy module
import pandas as pd
import numpy as np

# 이산화 - 범주화
# 연속형 데이터를 간격 단위로 분할해서 값을 할당하는 작업을 이산화

# 구간생성
#count, bin_dividers = np.histogram(mpg["horsepower"], bins=3)
#print(count)
#print(bin_dividers)

   18.0  8  307.0  130.0   3504.  12.0  70  1 chevrolet chevelle malibu
0  15.0  8  350.0  165.0  3693.0  11.5  70  1         buick skylark 320
1  18.0  8  318.0  150.0  3436.0  11.0  70  1        plymouth satellite
2  16.0  8  304.0  150.0  3433.0  12.0  70  1             amc rebel sst
3  17.0  8  302.0  140.0  3449.0  10.5  70  1               ford torino
4  15.0  8  429.0  198.0  4341.0  10.0  70  1          ford galaxie 500


In [13]:
mpg = pd.read_csv('/content/auto-mpg.csv')
print(mpg.head())

   18.0  8  307.0  130.0   3504.  12.0  70  1 chevrolet chevelle malibu
0  15.0  8  350.0  165.0  3693.0  11.5  70  1         buick skylark 320
1  18.0  8  318.0  150.0  3436.0  11.0  70  1        plymouth satellite
2  16.0  8  304.0  150.0  3433.0  12.0  70  1             amc rebel sst
3  17.0  8  302.0  140.0  3449.0  10.5  70  1               ford torino
4  15.0  8  429.0  198.0  4341.0  10.0  70  1          ford galaxie 500


In [20]:
print(dir(mpg))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul_

In [23]:
print(mpg)

     18.0  8  307.0  130.0   3504.  12.0  70  1 chevrolet chevelle malibu
0    15.0  8  350.0  165.0  3693.0  11.5  70  1         buick skylark 320
1    18.0  8  318.0  150.0  3436.0  11.0  70  1        plymouth satellite
2    16.0  8  304.0  150.0  3433.0  12.0  70  1             amc rebel sst
3    17.0  8  302.0  140.0  3449.0  10.5  70  1               ford torino
4    15.0  8  429.0  198.0  4341.0  10.0  70  1          ford galaxie 500
..    ... ..    ...    ...     ...   ...  .. ..                       ...
392  27.0  4  140.0  86.00  2790.0  15.6  82  1           ford mustang gl
393  44.0  4   97.0  52.00  2130.0  24.6  82  2                 vw pickup
394  32.0  4  135.0  84.00  2295.0  11.6  82  1             dodge rampage
395  28.0  4  120.0  79.00  2625.0  18.6  82  1               ford ranger
396  31.0  4  119.0  82.00  2720.0  19.4  82  1                chevy s-10

[397 rows x 9 columns]


In [27]:
age = np.array([[13], [30], [67], [36], [64], [24]])
#pandas의 메서드들은 DataFrame이나 Series를 이용해서 작업
#machine learning 관련된 메서드들은 2차원 이상의 ndarray를 가지고 작업을 수행
#30이 안되면 0, 30이상이면 1로 변환
#bins에는 여러 개의 데이터 설정이 가능
result = np.digitize(age, bins=[30])
print(result)

[[0]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [28]:
# Binarizer를 이용한 구간 분할
from sklearn.preprocessing import Binarizer
#threshold(임계값)
#흑백 이미지 데이터에서 뚜렷한 구분하기 위해서 임계값을 설정해서
#임계값 아래 와 위를 구분합니다.
binarizer = Binarizer(threshold=30.0)
print(binarizer.transform(age))

[[0]
 [0]
 [1]
 [1]
 [1]
 [0]]


In [32]:
from sklearn.preprocessing import KBinsDiscretizer

#균등한 분포로 4분할
#ordinal:라벨 인코딩 - 일련번호
kb = KBinsDiscretizer(4, encode='ordinal', strategy='quantile')
print(kb.fit_transform(age))
kb = KBinsDiscretizer(4, encode='onehot', strategy='quantile')
print(kb.fit_transform(age))
kb = KBinsDiscretizer(4, encode='onehot-dense', strategy='quantile')
print(kb.fit_transform(age))

[[0.]
 [1.]
 [3.]
 [2.]
 [3.]
 [0.]]
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (3, 2)	1.0
  (4, 3)	1.0
  (5, 0)	1.0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [36]:
# KMeans 알고리즘을 이용한 군집의 결과를 컬럼으로 추가

from sklearn.cluster import KMeans

#샘플 데이터 - DataFrame에서 추출하는 것이 일반적
sample = np.array([[13,30],[21,99],[21,33],[98,22],[20,87]])

dataFrame = pd.DataFrame(sample, columns=['f1', 'f2'])

# print(dataFrame)

clustering = KMeans(3, random_state=42)
clustering.fit(sample)
dataFrame['group'] = clustering.predict(sample)
print(dataFrame)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


   f1  f2  group
0  13  30      2
1  21  99      1
2  21  33      2
3  98  22      0
4  20  87      1


In [51]:
# 이상치 탐지
# 직접 수식을 작성해서 탐지
# 이상치 탐지를 위한 데이터 생성
features = np.array([[10, 10, 7, 6, 4, 5, 3, 3],[20000, 10, 7, 6, 4, 5, 3, 3]])

#z-score를 이용해서 이상치를 탐색해주는 함수
def outliers_z_score(ys):
  #임계값설정
  threshold=3

  #평균 구하기
  mean_y = np.mean(ys)

  #중앙값 구하기
  # mean_y = np.median(ys)

  # median_absolute_deviation_y = np.median([np.abs(y-median_y) for y in ys])

  #표준편차 구하기
  stdev_y = np.std(ys)
  z_scores = [(y-mean_y) / stdev_y for y in ys]
  print("Z_score", z_scores)

print(outliers_z_score(features))


Z_score [array([-0.25731729, -0.25731729, -0.25793714, -0.25814376, -0.258557  ,
       -0.25835038, -0.25876361, -0.25876361]), array([ 3.87298286, -0.25731729, -0.25793714, -0.25814376, -0.258557  ,
       -0.25835038, -0.25876361, -0.25876361])]
None


In [53]:
#IQR을 이용하는 방법
#boxplot을 그렸을 때 수염의 바깥쪽에 있는 데이터를 이상치로 간주

def outliers_iqr(ys):
  quartile_1, quartile_3 = np.percentile(ys, [25, 75])
  iqr = quartile_3 - quartile_1

  #하한과 상한 구하기
  lower_bound = quartile_1 - (iqr *1.5)
  upper_bound = quartile_3 + (iqr *1.5)


  return np.where((ys > upper_bound) | (ys < lower_bound))

features = np.array([[10, 10, 7, 6, 4, 5, 3, 3],[20000, 10, 7, 6, 4, 5, 3, 3]])
print(outliers_iqr(features))

print(outliers_iqr(mpg[['horsepower']].values))


(array([1]), array([0]))


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [54]:
#데이터를 생성해주는 API

In [55]:
from sklearn.datasets import make_blobs
#일정한 비율을 이상치로 간주하는 API
from sklearn.covariance import EllipticEnvelope

#2행 10행의 데이터를 랜덤하게 생성
#_는 데이터를 사용하지 않음
features, _ = make_blobs(n_samples=10, n_features=2, random_state=42)
#이상치 생성 - 0번 데이터는 이상한 데이터
features[0,0] = 10000
features[0,1] = 1000

print(features)

outlier_detector = EllipticEnvelope(contamination=0.1)
outlier_detector.fit(features)
#-1 이면 이상치 1이면 정상적인 데이터
outlier_detector.predict(features)

[[ 1.00000000e+04  1.00000000e+03]
 [-7.42400992e+00 -6.76918700e+00]
 [ 3.62704772e+00  2.28741702e+00]
 [-6.81209899e+00 -8.30485778e+00]
 [-2.26723535e+00  7.10100588e+00]
 [-2.97867201e+00  9.55684617e+00]
 [-9.29984808e-01  9.78172086e+00]
 [ 2.91496100e+00  1.41088215e+00]
 [ 3.73185476e+00  5.60865983e-01]
 [-2.97261532e+00  8.54855637e+00]]


array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [ ]:
from google.colab import files
myfile = files.upload()

from google.colab import drive
drive.mount('/content/drive')

pd.read_csv('/content/auto-mpg.csv')

mpg = pd.read_csv('/content/auto-mpg.csv')
print(mpg.head())

In [56]:
from google.colab import files
myfile = files.upload()


Saving log.txt to log.txt


In [57]:

from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [58]:

pd.read_csv('/content/log.txt')

log = pd.read_csv('/content/log.txt')
print(log.head())

  180.76.15.5 - - [15/Nov/2015:03:45:45 +0000] "GET / HTTP/1.1" 200 6812
0  180.76.15.143 - - [15/Nov/2015:03:46:26 +0000]...                    
1  180.76.15.25 - - [15/Nov/2015:03:46:27 +0000] ...                    
2  52.27.124.159 - - [15/Nov/2015:03:46:26 +0000]...                    
3  180.76.15.6 - - [15/Nov/2015:03:46:34 +0000] "...                    
4  61.160.213.32 - - [15/Nov/2015:03:50:37 +0000]...                    
