<a href="https://colab.research.google.com/github/20195114/Detectron/blob/main/2024_02_06__%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1부터 10까지 홀수를 가진 배열을 생성
import numpy as np
ar = np.arange(1, 10, 2)
print(ar)

[1 3 5 7 9]


In [4]:
# 의미없는 값으로 배열을 생성
ar = np.empty(10)
print(ar)

[4.86189404e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 2.87832081e+180 7.61482389e+169 7.73804033e-091
 1.72537235e-047 8.14023178e-315]


In [9]:
# 주 대각선 방향이 1인 3 * 3 정방 행렬 생성
ar = np.eye(3)
print(ar)

# 행렬에서 주 대각선의 데이터만 골라서 배열을 생성
print(np.diag(ar))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [14]:
# 데이터 타입 확인과 형 변환
import numpy as np
ar = np.array([1, "2", 3]) # 숫자와 문자열을 가지고 배열을 생성 - 문자
print(ar.dtype)

br = np.array([1, 2.3, 3]) # 정수와 실수 혼합
print(br.dtype)

# ar 배열에서 자료형을 변수로 변환
cr = np.array(np.int32)
print(cr.dtype)

<U21
float64
object


In [16]:
import numpy as np
# 0부터 19까지의 숫자를 가지고 1차원 배열 생성
ar = np.arange(20)
print(ar)

#ar 을 4*5 짜리 2차원 배열 생성
ar = np.arange(20)
print(ar)

#ar 을 4*5 짜리 2차원 배열로 변환
# 5를 대신에 -1을 대입해도 결과는 동일 합니다.
#20 개의 데이터는 4행으로 만들려면 5열 밖에 안됩니다.
matrix = ar.reshape((4,-1))
print(matrix)

#다차원 데이터를 1차원으로 변환
# br = matrix.reshape(-1)
br = matrix.flatten()
print(br)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
ar = np.arange(10)
matrix = ar.reshape((2,-1))

print(ar[0])
print(ar[-1])

print(matrix[0,2])
print(matrix [0][2])

0
9
2
2


In [24]:
# 배열에서 범위를 이용한 접근
ar = np.arange(10)
matrix = ar.reshape((2,-1))

print(ar[1:4])
print(ar[5:])
print(ar[:4])
print(ar[:])


# 이차원 배열에서의 접근
print(matrix[1][1:3])
print(matrix[1])
print(matrix[:,1])

[1 2 3]
[5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[6 7]
[5 6 7 8 9]
[1 6]


In [28]:
# 배열 생성
ar = np.arange(10)
print(ar)
# 범위를 이용해서 데이터를 가져오는 것 - 참조를 복사합니다.
br = ar[0:4].copy() # 데이터를 복제해서 br 이 가리키도록 합니다.
print(br)
# br[0] 을 수정하면 ar 의 데이터도 영향을 받게 됩니다.
br[0] = 42
print(br)
print(ar)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[42  1  2  3]
[0 1 2 3 4 5 6 7 8 9]


In [30]:
ar = np.arange(10)

#Fanch indexing
#데이터를 복제합니다.
br = ar[[1, 3, 5, 7]]
print(br)
br[0]= 15700
print(br)
print(ar)


[1 3 5 7]
[15700     3     5     7]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
matrix = ar.reshape((2,-1))
print(matrix)

print(matrix[:, 0])
# 이차원 배열에서 list를 이용해서 행 번호나 열 번호를 지정하면 이차원 배열이 만들어집니다.
print(matrix[:, [0]])
# numpy의 ndarray 나 pandas 의 DataFrame 에서
# 하나의 열을 선택할 때 list로 설정하는 경우는 구조를 유지하기 위해서 입니다.

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 5]
[[0]
 [5]]


In [38]:
print([1, 2, 3] and [1, 2, 3])

print(bool([1, 2, 3] and [1, 2, 3]))
print(bool([1, 2, 3] and []))

[1, 2, 3]
True
False


In [42]:
# 이차원 배열
matrix = ar.reshape((2, -1))
# 브로드캐스트 연산
# 차원이 다른 경우 차원을 순회하면서 연산을 수행
print(matrix + 10)
data = np.array([100, 200, 300, 400, 500])
print(matrix + data)

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[100 201 302 403 504]
 [105 206 307 408 509]]


In [45]:
print(matrix)
print(ar)
# 브로드캐스트 연산
# numpy의 ndarray 와 논리연산을 수행하면 bool 배열의 만들어 집니다.
print(ar == 3)
# 인덱스의 bool 배열을 대입하면 True 인 데이터만 추출됩니다.
print(ar[ar % 2 == 1])
# 홀수이거나 4의 배수이 데이터만 골라내기
print(ar[(ar % 2 == 1) | (ar % 4 == 0)])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[False False False  True False False False False False False]
[1 3 5 7 9]
[0 1 3 4 5 7 8 9]
